### ISSUE TITLE
Please add documentation 

### ISSUE THREAD

**Issue by imjeffparedes** [areessiapno/smart-sms-suite-api#1]
Please create DOCUMENTATION.md
Follow template below:

## :memo: Documentation

You can see below the API reference of this module.

### `<Class Name>(options)`
Creates the instance of the `<Class Name>` class.

#### Params
 - **String** `<parameter name>`: API username (mandatory).
 - **String** `<parameter name>` : API password (mandatory).
 - **Integer** `timeout` : integer containing the number of milliseconds to wait for a server to send response headers (and start the response body) before aborting the request.  (Optional default: 60000).

### `<function name>(numer,message, cb)`
Send outgoing sms request to api

#### Params

 - **String** `number` : <description> (mandatory)
 - **String**  `message` <description> (mandatory)
 - **Function**  `cb` The callback function.

**Comment by areessiapno** [comment]
Hi Sir Jeff,

DOCUMENTATION.md is completed.
Please see link below:
https://github.com/areessiapno/smart-sms-suite-api/blob/master/DOCUMENTATION.md


Thank you and Best Regards
Arees Siapno
Project Management and Development
