### ISSUE TITLE
Please add repository details

### ISSUE THREAD

**Issue by imjeffparedes** [areessiapno/smart-sms-suite-api#2]
Add repository details on package.json

  "repository": {
    "type": "git",
    "url": "git+ssh://git@github.com/<username>/<repository name>.git"
  }

**Comment by areessiapno** [comment]
Hi Sir Jeff,

package.json repository details updated.
Please see link below for your reference:
https://github.com/areessiapno/smart-sms-suite-api/blob/master/package.json

Thank you and Best Regards,
*Arees Siapno *
Project Management and Development
